import { Users, AlertTriangle, ClipboardCheck, TrendingUp } from "lucide-react";
import StatCard from "../components/StatCard.jsx";
import AlertCard from "../components/AlertCard.jsx";

// TODO: replace mock data with GET /api/dashboard once backend is wired up
const stats = [
  { label: "Youth in care", value: 48, tone: "primary", icon: Users },
  { label: "Active risk flags", value: 5, tone: "risk", icon: AlertTriangle },
  { label: "IDPs due this week", value: 9, tone: "amber", icon: ClipboardCheck },
  { label: "Avg. progress score", value: "76%", tone: "primary", icon: TrendingUp },
];

const alerts = [
  {
    youthId: "YT-0231",
    name: "J. Dela Cruz",
    age: 15,
    flag: "Sudden drop in group participation, 3 sessions",
    risk: "high",
    updatedAt: "12 min ago",
  },
  {
    youthId: "YT-0198",
    name: "M. Santos",
    age: 13,
    flag: "Sleep disturbance reported by houseparent",
    risk: "medium",
    updatedAt: "1 hr ago",
  },
  {
    youthId: "YT-0117",
    name: "R. Aquino",
    age: 16,
    flag: "Missed 2 consecutive counseling sessions",
    risk: "high",
    updatedAt: "3 hrs ago",
  },
  {
    youthId: "YT-0304",
    name: "A. Reyes",
    age: 14,
    flag: "Positive trend — recommend IDP milestone review",
    risk: "low",
    updatedAt: "Yesterday",
  },
];

export default function Dashboard() {
  return (
    <div className="space-y-8">
      <section className="grid grid-cols-2 lg:grid-cols-4 gap-4">
        {stats.map((s) => (
          <StatCard key={s.label} {...s} />
        ))}
      </section>

      <section>
        <div className="flex items-center justify-between mb-4">
          <div>
            <h2 className="font-display text-lg font-bold text-ink900">
              Behavioral risk alerts
            </h2>
            <p className="text-sm text-muted">
              Generated by the AI module — tap a case to review and take action.
            </p>
          </div>
          <button className="text-sm font-semibold text-primary hover:text-primary-dark">
            View all →
          </button>
        </div>

        <div className="space-y-3">
          {alerts.map((a) => (
            <AlertCard key={a.youthId} {...a} />
          ))}
        </div>
      </section>
    </div>
  );
}
